### ISSUE TITLE
no recordings are listed (no database entries for encoded files)

### ISSUE THREAD

**Issue by mspiceland** [ear9mrn/MythRokuPlayer#16] opened 2012-06-29 02:54 UTC
I am getting now recordings when running mythtv_xml.php?type=rec or mythtv_test.php?type=rec.  From looking at the source, it appears that xml_data.php looks in the mythconverg database at the recordings table for files with a basename of *.mp4.  I don't see where this is supposed to come from.  The rokuencode.sh script does not do an insert into the database.

I used MythRokuPlayer about a year ago and had no problems.  At that time, the php code looked at the .mpg recordings and looked in the directory structure to see if a .mp4 version of the .mpg existed.  It looks like following commit (a pull request from zane131) may have introduced the issue.

https://github.com/ear9mrn/MythRokuPlayer/commit/a3e01acfbf708961e085bc0ee7c626502fa549ae

zane131, any ideas on how to resolve this?  Is there another change that is needed that does the database insert after the .mp4 is created?

**Comment by zane131** [comment] 2012-06-29 04:00
I think MythBackend updates the database for you if you have set up the user job correctly. It's been a long time since I set it up. I'll have to investigate it this weekend.

**Comment by mspiceland** [comment] 2012-06-29 14:25
I did revert back to the revision before this commit and demonstrated that the recordings do show up using the old method (checking the directory for the existence of the .mp4 files).  They won't stream (only buffer halfway), but that is some other problem that I'll look into :-/  

zane131, thanks for your time.

**Comment by zane131** [comment] 2012-07-01 04:10
The previous commit was already filtering for .mp4 files:
    SELECT \* FROM recorded WHERE filename LIKE '%.mp4'

Now one thing that I did change (for recordings) was to use basename, instead of filename. Maybe prior to MythTV version .24, the SQL table used filename instead. What version are you using?

**Comment by rshendershot** [comment] 2012-07-05 15:21
zane - are you using the update databse in your rocuencode?  that probably should be merged up to master...

**Comment by zane131** [comment] 2012-07-05 21:03
@rshendershot I don't use rokuencode. I know I did dabble a little with it and have some code that does update the database, but I don't think it was complete. I will look at that code some time this weekend.

**Comment by zane131** [comment] 2012-10-01 02:36
At a high level the code filters files with a query like this:

```
SELECT * FROM recorded
WHERE ( basename LIKE '%.mp4' OR
        basename LIKE '%.m4v' OR
        basename LIKE '%.mov' );
```

So this query requires that the database be updated to contain the file names of the transcoded recordings. One solution is to modify rokuencode.sh to update the database after encoding.

I think the way this worked before is that it utilized the power of MythWeb by using URLs like this:

```
http://<mythweb_path>/p1/stream/<channel_id>/<start_time>
```

This will let MythWeb decide which video file to stream, preferring to use transcoded files first. The problem is that if a transcoded file does not exist, the player simply exits playback with no indication of why the file did not play. This was part of the motivation to add the filtering query above. I will investigate if there is any way to tell the user that a file needs to be transcoded.

**Comment by zane131** [comment] 2012-10-04 02:48
I added a potential solution to this issue my dev branch. Please check it out.

**Comment by rshendershot** [comment] 2014-02-13 15:40
rokuencode.sh has been updated.  if there are any remaining problems please open a new issue.

**Closed as completed by rshendershot** 2014-02-13 15:40 UTC
