### ISSUE TITLE
Showing: 0 to NaN of 0 files  

### ISSUE THREAD

**Issue by mschiller302** [ear9mrn/MythRokuPlayer#20] opened 2012-09-30 20:56 UTC
I downloaded the mythweb client using the github zip feature with the filename: ear9mrn-MythRokuPlayer-7c032db.zip

When I attempted to access:
http://192.168.0.4/mythweb/mythroku/mythtv_test.php?type=rec

I get:

<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>MythRoku Test Page</title>
</head>
<body bgcolor="white" text="blue">

<h1>MythRoku Test Page:
                     Recordings</h1>

```
            Use this page to help diagnose any problems there may be with settings and configuration. If all data displays ok here then it should work with Roku!
            <br><h2>Showing: 0 to NaN of 0 files</h2>
```

<b>Index 0</b><br><table border="1"><tr><td><a href="http://192.168.0.4/mythroku/mythtv_test.php?type=rec&amp;test=&amp;index=0"><img src="http://192.168.0.4/mythroku/images/Mythtv_movie.png" width="200" height="250"></a></td></tr></table>
<br>
</body>
</html>

I also get the following errors  in my apache error log corresponding with loading that page

[Sun Sep 30 15:54:20 2012] [error] [client 192.168.0.4] PHP Warning:  mysql_num_rows() expects parameter 1 to be resource, boolean given in /usr/share/mythtv/mythweb/mythroku/xml_data.php on line 68
[Sun Sep 30 15:54:20 2012] [error] [client 192.168.0.4] PHP Warning:  mysql_fetch_assoc() expects parameter 1 to be resource, boolean given in /usr/share/mythtv/mythweb/mythroku/xml_data.php on line 228
[Sun Sep 30 15:54:20 2012] [error] [client 192.168.0.4] File does not exist: /var/www/favicon.ico

I have three programs showing in mythweb and all of them have been transcoded...

Any ideas?

**Comment by zane131** [comment] 2012-10-01 00:56
What do you get when you run this query?

```
$ mysql --user=<user_name> --password=<your_password> <db_name>
mysql> SELECT basename FROM recorded;
```

**Comment by mschiller302** [comment] 2012-10-01 01:37
mysql --user=mythtv --password=<password> mythconverg
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 193
Server version: 5.5.24-0ubuntu0.12.04.1 (Ubuntu)

Copyright (c) 2000, 2011, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> SELECT basename FROM recorded;
+-------------------------+
| basename                |
+-------------------------+
| 2069_20120928120000.mpg |
| 1992_20120927200100.mpg |
| 2069_20120928123000.mpg |
+-------------------------+
3 rows in set (0.00 sec)

mysql>

For reference my settings.php is:
<?php

$WebServer = "http://192.168.0.4/mythweb";    // include path to mythweb eg, http://yourip/mythweb

$MythRokuDir = $WebServer . "/mythroku";    // name of your mythroku directory in the mythweb folder
$mythtvdata  = $WebServer . "/data";        // relative path to mythtv data

$RokuDisplayType = "HD";    // set to the same as your Roku player under display type, HD or SD

$MysqlServer  = "192.168.0.4";  // mysql server ip/name
$MythTVdb     = "mythconverg";  // mythtv database name
$MythTVdbuser = "mythtv";       // mythtv database user
$MythTVdbpass = "<password>";       // mythtv database password

$ResultLimit = 50;  // Maximum number of elements to be displayed at one time. Use 0 for no limit.

?>

**Comment by zane131** [comment] 2012-10-01 02:36
This is a duplicate of issue #16. I am going to close this issue and request all further discussion on this issue be done in issue #16.

**Closed as completed by zane131** 2012-10-01 02:36 UTC
